env:
  browser: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
plugins:
  - unicorn
  - "@typescript-eslint"
rules:
  unicorn/prefer-top-level-await: off
  no-await-in-loop: error
root: true
