env:
  browser: true
  es2022: true
extends:
  - standard-with-typescript
  - plugin:unicorn/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
plugins:
  - unicorn
rules:
  unicorn/prefer-top-level-await: off
