name: Deploy Crobot Service

on: [push]  # Adjust this as per your triggering needs.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository if needed
    - name: Checkout
      uses: actions/checkout@v2

    # Install openconnect
    - name: Install openconnect
      run: |
        sudo apt-get update
        sudo apt-get install -y openconnect

    # Connect to GlobalProtect using openconnect
    - name: Connect to GlobalProtect
      run: |
        echo "${{ secrets.ANU_PASSWORD }}" | sudo openconnect https://student-access.anu.edu.au -u ${{ secrets.ANU_USERNAME }} --passwd-on-stdin --protocol=gp --background

    # SSH and deploy the application
    - name: SSH and deploy application
      run: |
        # SSH into the server with the admin user
        sshpass -p "${{ secrets.ANU_PASSWORD }}" ssh -o StrictHostKeyChecking=no -t ${ANU_USERNAME}@cssa.anu.edu.au '
          # Run commands using sudo without a password prompt
          echo "${{ secrets.ANU_PASSWORD }}" | sudo -S su - ${CROBOT_DEPLOY_USER} -c "
            # Ensure we are in the right directory
            cd /usr/local/libexec/crobot || exit 1

            # Pull the latest changes
            git pull origin master

            # Your build commands go here
            # Example: ./build.sh or make
          "

          # Restart the crobot service with the original admin user
          echo "${{ secrets.ANU_PASSWORD }}" | sudo -S systemctl restart crobot
        '
      env:
        ANU_USERNAME: ${{ secrets.ANU_USERNAME }}
        CROBOT_DEPLOY_USER: ${{ secrets.CROBOT_DEPLOY_USER }}
